#!/usr/bin/env node
/**
 * FOLD TRANSLATIONS INTO A PACK — `node scripts/i18n-merge.mjs fr batch.json`.
 *
 * A pack is a plain module so the app can import it and a person can read it,
 * which makes it an awkward thing to edit in bulk: 1,500 rows have to stay
 * sorted, quoted consistently, and keyed on English that matches the catalogue
 * to the character. So translations arrive as JSON — `{ "English": "French" }`,
 * the shape a translator naturally works in — and this writes the module.
 *
 * It REFUSES a key the catalogue does not have. A near-miss (a curly quote
 * typed straight, a trailing full stop) would otherwise land silently in the
 * pack, translate nothing, and show up only as a stale row much later; failing
 * here points at the typo while it is still in front of you.
 *
 * Existing rows survive unless the batch names them, so a pack can be filled in
 * as many passes as it takes.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIR = join(ROOT, 'src', 'lib', 'i18n');
const NAMES = { es: 'Spanish', fr: 'French', de: 'German', it: 'Italian' };

const [lang, batchPath] = process.argv.slice(2);
if (!NAMES[lang] || !batchPath) {
  console.error('usage: i18n-merge.mjs <es|fr|de|it> <batch.json>');
  process.exit(2);
}

const catalogue = JSON.parse(readFileSync(join(DIR, 'strings.json'), 'utf8'));
const known = new Map(catalogue.map((r) => [r.en, r]));
const batch = JSON.parse(readFileSync(batchPath, 'utf8'));

const file = join(DIR, `${lang}.js`);
const existing = existsSync(file) ? (await import(pathToFileURL(file).href)).default || {} : {};

const holesOf = (s) => new Set([...s.matchAll(/\{(\d+)\}/g)].map((m) => m[1]));
const merged = { ...existing };
let added = 0;
let changed = 0;
const problems = [];

for (const [en, to] of Object.entries(batch)) {
  const row = known.get(en);
  if (!row) { problems.push(`not in the catalogue: ${JSON.stringify(en.slice(0, 70))}`); continue; }
  if (row.ambiguous) { problems.push(`deliberately untranslated (adjacent holes): ${JSON.stringify(en.slice(0, 50))}`); continue; }
  if (!to || typeof to !== 'string') { problems.push(`empty translation for ${JSON.stringify(en.slice(0, 50))}`); continue; }
  const want = holesOf(en);
  const got = holesOf(to);
  const lost = [...want].filter((h) => !got.has(h));
  const extra = [...got].filter((h) => !want.has(h));
  if (lost.length || extra.length) {
    problems.push(`placeholders wrong in ${JSON.stringify(en.slice(0, 50))}` +
      (lost.length ? ` — lost {${lost.join('} {')}}` : '') +
      (extra.length ? ` — invented {${extra.join('} {')}}` : ''));
    continue;
  }
  if (merged[en] === to) continue;
  if (merged[en] === undefined) added++; else changed++;
  merged[en] = to;
}

if (problems.length) {
  console.error(`${problems.length} problem(s) — nothing written:`);
  for (const p of problems.slice(0, 20)) console.error('  ' + p);
  process.exit(1);
}

const q = (s) => "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
const body = Object.keys(merged).sort((a, b) => a.localeCompare(b))
  .map((en) => '  ' + q(en) + ': ' + q(merged[en]) + ',').join('\n');

writeFileSync(file, `/**
 * ${NAMES[lang]} — the interface, keyed on the English exactly as it renders.
 *
 * Generated by \`scripts/i18n-merge.mjs\` from hand-written translations.
 * \`npm run i18n:check\` reports every string still missing and every key the
 * app no longer shows, so this file and the screens cannot drift apart. A
 * missing key renders in English rather than blank, which is the only safe way
 * to fail — and a language is not offered at all until this file is complete.
 *
 * A \`{0}\` is a value the app drops in: a shop's name, a count, a realm's own
 * word for "region". Keep every hole the English has, and put them wherever
 * this language needs them — the runtime substitutes by NUMBER, not by order.
 */
export default {
${body}
};
`);

const total = Object.keys(merged).length;
const want = catalogue.filter((r) => !r.ambiguous).length;
console.log(`${lang}: +${added} new, ${changed} changed → ${total}/${want} (${Math.round((total / want) * 100)}%)`);
